steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/edgelab2',
      '--build-arg', 'VITE_GEMINI_API_KEY=$_GEMINI_API_KEY',
      '--build-arg', 'VITE_ODDS_API_KEY=$_ODDS_API_KEY',
      '--build-arg', 'VITE_SUPABASE_URL=$_SUPABASE_URL',
      '--build-arg', 'VITE_SUPABASE_ANON_KEY=$_SUPABASE_KEY',
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/edgelab2'